"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { employmentStatusSchema, staffTypeSchema } from "@/lib/staff-members";
import { requireAdmin } from "@/lib/staff/auth";
import { createClient } from "@/lib/supabase/server";

export type StaffMemberFormState = { formError?: string; fieldErrors?: Partial<Record<"employee_code" | "full_name" | "staff_type" | "designation" | "employment_status" | "phone" | "email" | "joining_date", string>> };
const schema = z.object({ id: z.string().uuid().optional(), employee_code: z.string().trim().min(1, "Enter an employee ID.").max(40), full_name: z.string().trim().min(1, "Enter the employee’s full name.").max(140), staff_type: staffTypeSchema, designation: z.string().trim().min(1, "Enter a designation.").max(140), employment_status: employmentStatusSchema, phone: z.string().trim().max(30), email: z.string().trim().max(254).refine((value) => !value || z.string().email().safeParse(value).success, "Enter a valid email address."), joining_date: z.string().trim().refine((value) => !value || /^\d{4}-\d{2}-\d{2}$/.test(value), "Enter a valid joining date.") });
function invalid(result: z.ZodSafeParseError<unknown>): StaffMemberFormState { const fieldErrors: StaffMemberFormState["fieldErrors"] = {}; for (const issue of result.error.issues) { const field = String(issue.path[0]); if (field in { employee_code: 1, full_name: 1, staff_type: 1, designation: 1, employment_status: 1, phone: 1, email: 1, joining_date: 1 }) fieldErrors[field as keyof NonNullable<StaffMemberFormState["fieldErrors"]>] = issue.message; } return { formError: "Please review the highlighted employee details.", fieldErrors }; }
function revalidateStaff() { revalidatePath("/staff"); revalidatePath("/staff/staff"); }
async function save(formData: FormData, editing: boolean): Promise<StaffMemberFormState> { await requireAdmin(); const parsed = schema.safeParse({ id: formData.get("id") || undefined, employee_code: formData.get("employee_code"), full_name: formData.get("full_name"), staff_type: formData.get("staff_type"), designation: formData.get("designation"), employment_status: formData.get("employment_status"), phone: formData.get("phone"), email: formData.get("email"), joining_date: formData.get("joining_date") }); if (!parsed.success) return invalid(parsed); const input = { employee_code: parsed.data.employee_code, full_name: parsed.data.full_name, staff_type: parsed.data.staff_type, designation: parsed.data.designation, employment_status: parsed.data.employment_status, phone: parsed.data.phone || null, email: parsed.data.email || null, joining_date: parsed.data.joining_date || null }; const supabase = await createClient(); if (editing) { if (!parsed.data.id) return { formError: "We could not find this employee record." }; const { error } = await supabase.from("staff_members").update(input).eq("id", parsed.data.id); if (error) return { formError: error.code === "23505" ? "That employee ID is already in use." : "We could not save this employee record. Please try again." }; revalidateStaff(); redirect(`/staff/staff/${parsed.data.id}/edit?updated=1`); } const { data, error } = await supabase.from("staff_members").insert(input).select("id").single(); if (error || !data) return { formError: error?.code === "23505" ? "That employee ID is already in use." : "We could not save this employee record. Please try again." }; revalidateStaff(); redirect(`/staff/staff/${data.id}/edit?created=1`); }
export async function createStaffMember(_: StaffMemberFormState, formData: FormData) { return save(formData, false); }
export async function updateStaffMember(_: StaffMemberFormState, formData: FormData) { return save(formData, true); }
export async function deactivateStaffMember(formData: FormData) { await requireAdmin(); const id = z.string().uuid().safeParse(formData.get("id")); if (!id.success) redirect("/staff/staff"); const { error } = await (await createClient()).from("staff_members").update({ employment_status: "inactive" }).eq("id", id.data); if (error) redirect(`/staff/staff/${id.data}/edit?error=save`); revalidateStaff(); redirect(`/staff/staff/${id.data}/edit?updated=inactive`); }
