"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdmin } from "@/lib/staff/auth";
import { enrollmentSchema, studentSchema, validationErrors, type StudentFieldErrors } from "@/lib/student-validation";
import { createClient } from "@/lib/supabase/server";

const uuid=z.string().uuid();
const trim=(v:string)=>v.trim()||null;const paths=()=>["/staff","/staff/students","/staff/students/enrollments"].forEach((path)=>revalidatePath(path));const edit=(id:string)=>`/staff/students/${id}/edit`;const enrollmentEdit=(id:string)=>`/staff/students/${id}/enrollment`;
export type StudentCreateState={status:"idle"|"error";message?:string;fieldErrors:StudentFieldErrors};
const creationError=(message:string,fieldErrors:StudentFieldErrors={}):StudentCreateState=>({status:"error",message,fieldErrors});
export async function createStudent(_previousState:StudentCreateState,f:FormData):Promise<StudentCreateState>{await requireAdmin();const a=studentSchema.safeParse(Object.fromEntries(f));const e=enrollmentSchema.safeParse(Object.fromEntries(f));if(!a.success||!e.success)return creationError("Please review the highlighted fields.",validationErrors(a,e));const s=await createClient();const{data,error}=await s.rpc("create_student_with_enrollment",{p_admission_number:a.data.admission_number,p_full_name:a.data.full_name,p_date_of_birth:a.data.date_of_birth||null,p_gender:a.data.gender||null,p_father_guardian_name:trim(a.data.father_guardian_name),p_mother_name:trim(a.data.mother_name),p_primary_phone:trim(a.data.primary_phone),p_secondary_phone:trim(a.data.secondary_phone),p_email:trim(a.data.email),p_address_line_1:trim(a.data.address_line_1),p_address_line_2:trim(a.data.address_line_2),p_locality:trim(a.data.locality),p_city:trim(a.data.city),p_state:trim(a.data.state),p_postal_code:trim(a.data.postal_code),p_admission_date:a.data.admission_date,p_status:a.data.status,p_academic_year_id:e.data.academic_year_id,p_class_id:e.data.class_id,p_academic_section_id:e.data.academic_section_id,p_roll_number:trim(e.data.roll_number),p_enrollment_date:e.data.enrollment_date});if(error||!data){console.error("Student creation failed.",{operation:"createStudent",code:error?.code,message:error?.message,details:error?.details,hint:error?.hint});if(error?.code==="23505")return creationError("Admission number or roll number already exists.",{admission_number:["Admission number or roll number already exists."],roll_number:["Admission number or roll number already exists."]});if(error?.code==="23514"&&error.message.includes("Enrollment section must belong"))return creationError("The selected section does not belong to that academic year and class.",{academic_section_id:["Select a section configured for the chosen academic year and class."]});return creationError("Could not create student. Please try again.")}paths();redirect(`/staff/students/${data}?created=1`)}
export async function updateStudent(f:FormData){await requireAdmin();const id=uuid.safeParse(f.get("id"));const p=studentSchema.safeParse(Object.fromEntries(f));if(!id.success||!p.success)redirect(id.success?`${edit(id.data)}?error=invalid`:"/staff/students?error=invalid");const s=await createClient();const{data:exists}=await s.from("students").select("id").eq("id",id.data).maybeSingle();if(!exists)redirect("/staff/students?error=notfound");const{error}=await s.from("students").update({...p.data,date_of_birth:p.data.date_of_birth||null,gender:p.data.gender||null,father_guardian_name:trim(p.data.father_guardian_name),mother_name:trim(p.data.mother_name),primary_phone:trim(p.data.primary_phone),secondary_phone:trim(p.data.secondary_phone),email:trim(p.data.email),address_line_1:trim(p.data.address_line_1),address_line_2:trim(p.data.address_line_2),locality:trim(p.data.locality),city:trim(p.data.city),state:trim(p.data.state),postal_code:trim(p.data.postal_code)}).eq("id",id.data);if(error)redirect(`${edit(id.data)}?error=${error.code==="23505"?"duplicate":"save"}`);paths();revalidatePath(`/staff/students/${id.data}`);redirect(`/staff/students/${id.data}?updated=1`)}
export async function updateEnrollment(f:FormData){await requireAdmin();const studentId=uuid.safeParse(f.get("student_id"));const id=uuid.safeParse(f.get("id"));const p=enrollmentSchema.safeParse(Object.fromEntries(f));if(!studentId.success||!id.success||!p.success)redirect(studentId.success?`${enrollmentEdit(studentId.data)}?error=invalid`:"/staff/students?error=invalid");const s=await createClient();const{data:exists}=await s.from("student_enrollments").select("id").eq("id",id.data).eq("student_id",studentId.data).maybeSingle();if(!exists)redirect(`/staff/students/${studentId.data}?error=notfound`);const{error}=await s.from("student_enrollments").update({academic_year_id:p.data.academic_year_id,class_id:p.data.class_id,academic_section_id:p.data.academic_section_id,roll_number:trim(p.data.roll_number),status:p.data.enrollment_status,enrollment_date:p.data.enrollment_date}).eq("id",id.data);if(error){console.error("Enrollment update failed.",{operation:"updateStudentEnrollment",code:error.code,message:error.message,details:error.details,hint:error.hint});redirect(`${enrollmentEdit(studentId.data)}?error=${error.code==="23505"?"duplicate":error.code==="23514"?"section":"save"}`)}paths();revalidatePath(`/staff/students/${studentId.data}`);redirect(`/staff/students/${studentId.data}?enrollment=updated`)}
