"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdmin } from "@/lib/staff/auth";
import { enrollmentSchema, studentSchema, validationErrors, type StudentFieldErrors } from "@/lib/student-validation";
import { createClient } from "@/lib/supabase/server";

const uuid=z.string().uuid();
const trim=(v:string)=>v.trim()||null;const paths=()=>["/staff","/staff/students","/staff/students/enrollments"].forEach((path)=>revalidatePath(path));const edit=(id:string)=>`/staff/students/${id}/edit`;const enrollmentEdit=(id:string)=>`/staff/students/${id}/enrollment`;
const imageTypes=new Set(["image/jpeg","image/png","image/webp"]);const values=(f:FormData)=>({...Object.fromEntries(f),transport_required:f.get("transport_required")==="on"});const nullable=(data:Record<string,unknown>)=>Object.fromEntries(Object.entries(data).map(([key,value])=>[key,typeof value==="string"?trim(value):value]));
const maxStudentPhotoSize=4194304;
const photoExtension=(photo:File)=>photo.type==="image/jpeg"?"jpg":photo.type==="image/png"?"png":"webp";
const validStudentPhoto=async(photo:File)=>{if(!imageTypes.has(photo.type)||photo.size>maxStudentPhotoSize)return false;const bytes=new Uint8Array(await photo.slice(0,12).arrayBuffer());if(photo.type==="image/jpeg")return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(photo.type==="image/png")return[0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a].every((value,index)=>bytes[index]===value);return[0x52,0x49,0x46,0x46].every((value,index)=>bytes[index]===value)&&[0x57,0x45,0x42,0x50].every((value,index)=>bytes[index+8]===value)};
const studentPhotoPath=(studentId:string,photo:File)=>`student-photos/${studentId}/${crypto.randomUUID()}.${photoExtension(photo)}`;
const profile=(data:Record<string,unknown>)=>{const p=nullable(data);delete p.admission_number;delete p.full_name;delete p.date_of_birth;delete p.gender;delete p.admission_date;delete p.status;delete p.father_guardian_name;delete p.mother_name;delete p.primary_phone;delete p.secondary_phone;delete p.email;delete p.address_line_2;delete p.state;delete p.postal_code;delete p.academic_year_id;delete p.class_id;delete p.academic_section_id;delete p.roll_number;delete p.enrollment_date;delete p.enrollment_status;delete p.photo;return p};
export type StudentCreateState={status:"idle"|"error";message?:string;fieldErrors:StudentFieldErrors};
const creationError=(message:string,fieldErrors:StudentFieldErrors={}):StudentCreateState=>({status:"error",message,fieldErrors});
export type StudentEditState={status:"idle"|"error";message?:string;fieldErrors:StudentFieldErrors;values?:Record<string,FormDataEntryValue|undefined>};
const editError=(message:string,fieldErrors:StudentFieldErrors={},values?:Record<string,FormDataEntryValue|undefined>):StudentEditState=>({status:"error",message,fieldErrors,values});
const plainValues=(f:FormData)=>{const submitted:Record<string,FormDataEntryValue|undefined>={};f.forEach((value,key)=>{submitted[key]=typeof value==="string"?value:undefined});return submitted};
export async function createStudent(_previousState:StudentCreateState,f:FormData):Promise<StudentCreateState>{await requireAdmin();const input=values(f),a=studentSchema.safeParse(input),e=enrollmentSchema.safeParse(input);if(!a.success||!e.success)return creationError("Please review the highlighted fields.",validationErrors(a,e));const photo=f.get("photo");if(photo instanceof File&&photo.size&&!(await validStudentPhoto(photo)))return creationError("The profile photo must be a JPEG, PNG or WebP image up to 4 MB.",{photo:["Choose a supported image up to 4 MB."]});const s=await createClient();const{data,error}=await s.rpc("create_student_with_enrollment",{p_admission_number:a.data.admission_number,p_full_name:a.data.full_name,p_date_of_birth:a.data.date_of_birth||null,p_gender:a.data.gender||null,p_father_guardian_name:trim(a.data.father_guardian_name),p_mother_name:trim(a.data.mother_name),p_primary_phone:trim(a.data.primary_phone),p_secondary_phone:trim(a.data.secondary_phone),p_email:trim(a.data.email),p_address_line_1:null,p_address_line_2:trim(a.data.address_line_2),p_locality:null,p_city:null,p_state:trim(a.data.state),p_postal_code:trim(a.data.postal_code),p_admission_date:a.data.admission_date,p_status:a.data.status,p_academic_year_id:e.data.academic_year_id,p_class_id:e.data.class_id,p_academic_section_id:e.data.academic_section_id,p_roll_number:trim(e.data.roll_number),p_enrollment_date:e.data.enrollment_date});if(error||!data){console.error("Student creation failed.",{operation:"createStudent",code:error?.code,message:error?.message,details:error?.details,hint:error?.hint});return creationError("Could not create student. Please try again.")}const update=profile(a.data as Record<string,unknown>);if(photo instanceof File&&photo.size){const path=studentPhotoPath(data,photo),upload=await s.storage.from("student-photos").upload(path,photo,{contentType:photo.type,upsert:false});if(upload.error){paths();redirect(`/staff/students/${data}/edit?error=photo`)}const saved=await s.from("students").update({profile_photo_path:path,...update}).eq("id",data);if(saved.error){await s.storage.from("student-photos").remove([path]);console.error("Student profile update failed.",{operation:"createStudent",code:saved.error.code,message:saved.error.message,details:saved.error.details,hint:saved.error.hint});paths();redirect(`/staff/students/${data}/edit?error=profile`)}}else{const saved=await s.from("students").update(update).eq("id",data);if(saved.error){console.error("Student profile update failed.",{operation:"createStudent",code:saved.error.code,message:saved.error.message,details:saved.error.details,hint:saved.error.hint});paths();redirect(`/staff/students/${data}/edit?error=profile`)}}paths();redirect(`/staff/students/${data}?created=1`)}
export async function updateStudentState(_previousState:StudentEditState,f:FormData):Promise<StudentEditState>{await requireAdmin();const submitted=plainValues(f),id=uuid.safeParse(f.get("id")),input=values(f),parsed=studentSchema.safeParse(input);if(!id.success)return editError("Could not save student. Please try again.",{},submitted);if(!parsed.success)return editError("Please review the highlighted fields.",validationErrors(parsed),submitted);const photo=f.get("photo");if(photo instanceof File&&photo.size&&!(await validStudentPhoto(photo)))return editError("The profile photo must be a JPEG, PNG or WebP image up to 4 MB.",{photo:["Choose a supported image up to 4 MB."]},submitted);const s=await createClient();const{data:current,error:currentError}=await s.from("students").select("profile_photo_path").eq("id",id.data).maybeSingle();if(currentError||!current){console.error("Student lookup failed.",{operation:"updateStudentState",code:currentError?.code,message:currentError?.message,details:currentError?.details,hint:currentError?.hint});return editError("Could not save student. Please try again.",{},submitted)}const removePhoto=f.get("remove_photo")==="on";let newPath:string|null=null;if(photo instanceof File&&photo.size){newPath=studentPhotoPath(id.data,photo);const upload=await s.storage.from("student-photos").upload(newPath,photo,{contentType:photo.type,upsert:false});if(upload.error)return editError("We could not upload the profile photo. Please try again.",{},submitted)}const update=nullable(parsed.data as Record<string,unknown>);const photo_path=newPath??(removePhoto?null:current.profile_photo_path);const{error}=await s.from("students").update({...update,profile_photo_path:photo_path}).eq("id",id.data);if(error){if(newPath)await s.storage.from("student-photos").remove([newPath]);console.error("Student update failed.",{operation:"updateStudentState",code:error.code,message:error.message,details:error.details,hint:error.hint});return editError(error.code==="23505"?"Admission number already exists.":"Could not save student. Please try again.",error.code==="23505"?{admission_number:["Admission number already exists."]}:{},submitted)}if((newPath||removePhoto)&&current.profile_photo_path){const cleanup=await s.storage.from("student-photos").remove([current.profile_photo_path]);if(cleanup.error)console.error("Student photo cleanup failed.",{operation:"updateStudentState",code:cleanup.error.name,message:cleanup.error.message})}paths();revalidatePath(`/staff/students/${id.data}`);redirect(`/staff/students/${id.data}?updated=1`)}
export async function updateEnrollment(f:FormData){await requireAdmin();const studentId=uuid.safeParse(f.get("student_id"));const id=uuid.safeParse(f.get("id"));const p=enrollmentSchema.safeParse(Object.fromEntries(f));if(!studentId.success||!id.success||!p.success)redirect(studentId.success?`${enrollmentEdit(studentId.data)}?error=invalid`:"/staff/students?error=invalid");const s=await createClient();const{data:exists}=await s.from("student_enrollments").select("id").eq("id",id.data).eq("student_id",studentId.data).maybeSingle();if(!exists)redirect(`/staff/students/${studentId.data}?error=notfound`);const{error}=await s.from("student_enrollments").update({academic_year_id:p.data.academic_year_id,class_id:p.data.class_id,academic_section_id:p.data.academic_section_id,roll_number:trim(p.data.roll_number),status:p.data.enrollment_status,enrollment_date:p.data.enrollment_date}).eq("id",id.data);if(error){console.error("Enrollment update failed.",{operation:"updateStudentEnrollment",code:error.code,message:error.message,details:error.details,hint:error.hint});redirect(`${enrollmentEdit(studentId.data)}?error=${error.code==="23505"?"duplicate":error.code==="23514"?"section":"save"}`)}paths();revalidatePath(`/staff/students/${studentId.data}`);redirect(`/staff/students/${studentId.data}?enrollment=updated`)}
