"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdmin } from "@/lib/staff/auth";
import { enrollmentSchema, normalizeStudentFormData, studentEditPatch, studentEditSchema, studentFormStateValues, studentSchema, validationErrors, type StudentFieldErrors, type StudentFormStateValues } from "@/lib/student-validation";
import { createClient } from "@/lib/supabase/server";

const uuid=z.string().uuid();
const trim=(v:string)=>v.trim()||null;const paths=()=>["/staff","/staff/students","/staff/students/enrollments"].forEach((path)=>revalidatePath(path));const edit=(id:string)=>`/staff/students/${id}/edit`;const enrollmentEdit=(id:string)=>`/staff/students/${id}/enrollment`;
const imageTypes=new Set(["image/jpeg","image/png","image/webp"]);const nullable=(data:Record<string,unknown>)=>Object.fromEntries(Object.entries(data).map(([key,value])=>[key,typeof value==="string"?trim(value):value]));
const maxStudentPhotoSize=4194304;
const photoExtension=(photo:File)=>photo.type==="image/jpeg"?"jpg":photo.type==="image/png"?"png":"webp";
const validStudentPhoto=async(photo:File)=>{if(!imageTypes.has(photo.type)||photo.size>maxStudentPhotoSize)return false;const bytes=new Uint8Array(await photo.slice(0,12).arrayBuffer());if(photo.type==="image/jpeg")return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(photo.type==="image/png")return[0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a].every((value,index)=>bytes[index]===value);return[0x52,0x49,0x46,0x46].every((value,index)=>bytes[index]===value)&&[0x57,0x45,0x42,0x50].every((value,index)=>bytes[index+8]===value)};
const studentPhotoPath=(studentId:string,photo:File)=>`student-photos/${studentId}/${crypto.randomUUID()}.${photoExtension(photo)}`;
const profile=(data:Record<string,unknown>)=>{const p=nullable(data);delete p.admission_number;delete p.full_name;delete p.date_of_birth;delete p.gender;delete p.admission_date;delete p.status;delete p.father_guardian_name;delete p.mother_name;delete p.primary_phone;delete p.secondary_phone;delete p.email;delete p.address_line_2;delete p.state;delete p.postal_code;delete p.academic_year_id;delete p.class_id;delete p.academic_section_id;delete p.roll_number;delete p.enrollment_date;delete p.enrollment_status;delete p.photo;return p};
export type StudentCreateState={status:"idle"|"error";message?:string;fieldErrors:StudentFieldErrors;values?:StudentFormStateValues};
const creationError=(message:string,fieldErrors:StudentFieldErrors={},values?:StudentFormStateValues):StudentCreateState=>({status:"error",message,fieldErrors,values});
export type StudentEditState={status:"idle"|"error";message?:string;fieldErrors:StudentFieldErrors;values?:StudentFormStateValues};
const editError=(message:string,fieldErrors:StudentFieldErrors={},values?:StudentFormStateValues):StudentEditState=>({status:"error",message,fieldErrors,values});
export async function createStudent(_previousState:StudentCreateState,f:FormData):Promise<StudentCreateState>{await requireAdmin();const submitted=studentFormStateValues(f),input=normalizeStudentFormData(f),a=studentSchema.safeParse(input),e=enrollmentSchema.safeParse(input);if(!a.success||!e.success)return creationError("Please review the highlighted fields.",validationErrors(a,e),submitted);const photo=f.get("photo");if(photo instanceof File&&photo.size&&!(await validStudentPhoto(photo)))return creationError("The profile photo must be a JPEG, PNG or WebP image up to 4 MB.",{photo:["Choose a supported image up to 4 MB."]},submitted);const s=await createClient();const{data,error}=await s.rpc("create_student_with_enrollment",{p_admission_number:a.data.admission_number,p_full_name:a.data.full_name,p_date_of_birth:a.data.date_of_birth||null,p_gender:a.data.gender||null,p_father_guardian_name:trim(a.data.father_guardian_name),p_mother_name:trim(a.data.mother_name),p_primary_phone:trim(a.data.primary_phone),p_secondary_phone:trim(a.data.secondary_phone),p_email:trim(a.data.email),p_address_line_1:null,p_address_line_2:trim(a.data.address_line_2),p_locality:null,p_city:null,p_state:trim(a.data.state),p_postal_code:trim(a.data.postal_code),p_admission_date:a.data.admission_date,p_status:a.data.status,p_academic_year_id:e.data.academic_year_id,p_class_id:e.data.class_id,p_academic_section_id:e.data.academic_section_id,p_roll_number:trim(e.data.roll_number),p_enrollment_date:e.data.enrollment_date});if(error||!data){console.error("Student creation failed.",{operation:"createStudent",code:error?.code,message:error?.message,details:error?.details,hint:error?.hint});return creationError("Could not create student. Please try again.",{},submitted)}const update=profile(a.data as Record<string,unknown>);if(photo instanceof File&&photo.size){const path=studentPhotoPath(data,photo),upload=await s.storage.from("student-photos").upload(path,photo,{contentType:photo.type,upsert:false});if(upload.error){paths();redirect(`/staff/students/${data}/edit?error=photo`)}const saved=await s.from("students").update({profile_photo_path:path,...update}).eq("id",data);if(saved.error){await s.storage.from("student-photos").remove([path]);console.error("Student profile update failed.",{operation:"createStudent",code:saved.error.code,message:saved.error.message,details:saved.error.details,hint:saved.error.hint});paths();redirect(`/staff/students/${data}/edit?error=profile`)}}else{const saved=await s.from("students").update(update).eq("id",data);if(saved.error){console.error("Student profile update failed.",{operation:"createStudent",code:saved.error.code,message:saved.error.message,details:saved.error.details,hint:saved.error.hint});paths();redirect(`/staff/students/${data}/edit?error=profile`)}}paths();redirect(`/staff/students/${data}?created=1`)}
export async function updateStudentState(_previousState:StudentEditState,f:FormData):Promise<StudentEditState>{await requireAdmin();const submitted=studentFormStateValues(f),id=uuid.safeParse(f.get("id")),input=normalizeStudentFormData(f),parsed=studentEditSchema.safeParse(input);if(!id.success)return editError("Could not save student. Please try again.",{},submitted);if(!parsed.success)return editError("Please review the highlighted fields.",validationErrors(parsed),submitted);const photo=f.get("photo");if(photo instanceof File&&photo.size&&!(await validStudentPhoto(photo)))return editError("The profile photo must be a JPEG, PNG or WebP image up to 4 MB.",{photo:["Choose a supported image up to 4 MB."]},submitted);const s=await createClient();const{data:current,error:currentError}=await s.from("students").select("profile_photo_path").eq("id",id.data).maybeSingle();if(currentError||!current){console.error("Student lookup failed.",{operation:"updateStudentState",code:currentError?.code,message:currentError?.message,details:currentError?.details,hint:currentError?.hint});return editError("Could not save student. Please try again.",{},submitted)}const removePhoto=f.get("remove_photo")==="on";let newPath:string|null=null;if(photo instanceof File&&photo.size){newPath=studentPhotoPath(id.data,photo);const upload=await s.storage.from("student-photos").upload(newPath,photo,{contentType:photo.type,upsert:false});if(upload.error)return editError("We could not upload the profile photo. Please try again.",{},submitted)}const update=nullable(studentEditPatch(parsed.data,f));const photo_path=newPath??(removePhoto?null:current.profile_photo_path);const{error}=await s.from("students").update({...update,profile_photo_path:photo_path}).eq("id",id.data);if(error){if(newPath)await s.storage.from("student-photos").remove([newPath]);console.error("Student update failed.",{operation:"updateStudentState",code:error.code,message:error.message,details:error.details,hint:error.hint});return editError(error.code==="23505"?"Admission number already exists.":"Could not save student. Please try again.",error.code==="23505"?{admission_number:["Admission number already exists."]}:{},submitted)}if((newPath||removePhoto)&&current.profile_photo_path){const cleanup=await s.storage.from("student-photos").remove([current.profile_photo_path]);if(cleanup.error)console.error("Student photo cleanup failed.",{operation:"updateStudentState",code:cleanup.error.name,message:cleanup.error.message})}paths();revalidatePath(`/staff/students/${id.data}`);redirect(`/staff/students/${id.data}?updated=1`)}
const lifecycleBase=z.object({student_id:uuid,enrollment_id:uuid,effective_date:z.string().date(),reason:z.string().trim().max(500),confirm:z.literal("on")});
const lifecycleError=(code?:string)=>code==="23505"?"duplicate":code==="23514"?"invalid":code==="P0002"?"notfound":code==="42501"?"forbidden":"save";
async function finishLifecycle(studentId:string,operation:string,error?:{code?:string;message?:string;details?:string;hint?:string}){if(error){console.error("Student lifecycle action failed.",{operation,code:error.code,message:error.message,details:error.details,hint:error.hint});redirect(`${enrollmentEdit(studentId)}?error=${lifecycleError(error.code)}`)}paths();revalidatePath(`/staff/students/${studentId}`);redirect(`/staff/students/${studentId}?enrollment=${operation}`)}

export async function correctEnrollmentRoll(f:FormData){await requireAdmin();const p=z.object({student_id:uuid,enrollment_id:uuid,roll_number:z.string().trim().max(30),reason:z.string().trim().min(1).max(500)}).safeParse(Object.fromEntries(f));if(!p.success)redirect("/staff/students?error=invalid");const{error}=await(await createClient()).rpc("correct_student_enrollment_roll",{p_student_id:p.data.student_id,p_enrollment_id:p.data.enrollment_id,p_roll_number:p.data.roll_number,p_reason:p.data.reason});await finishLifecycle(p.data.student_id,"corrected",error??undefined)}
export async function promoteStudent(f:FormData){await requireAdmin();const p=z.object({student_id:uuid,source_enrollment_id:uuid,academic_year_id:uuid,class_id:uuid,academic_section_id:uuid,roll_number:z.string().trim().max(30),enrollment_date:z.string().date(),confirm:z.literal("on")}).safeParse(Object.fromEntries(f));if(!p.success)redirect("/staff/students?error=invalid");const{error}=await(await createClient()).rpc("promote_student",{p_student_id:p.data.student_id,p_source_enrollment_id:p.data.source_enrollment_id,p_target_academic_year_id:p.data.academic_year_id,p_target_class_id:p.data.class_id,p_target_section_id:p.data.academic_section_id,p_roll_number:p.data.roll_number,p_enrollment_date:p.data.enrollment_date});await finishLifecycle(p.data.student_id,"promoted",error??undefined)}
export async function transferStudent(f:FormData){await requireAdmin();const p=lifecycleBase.safeParse(Object.fromEntries(f));if(!p.success)redirect("/staff/students?error=invalid");const{error}=await(await createClient()).rpc("transfer_student",{p_student_id:p.data.student_id,p_enrollment_id:p.data.enrollment_id,p_effective_date:p.data.effective_date,p_reason:p.data.reason});await finishLifecycle(p.data.student_id,"transferred",error??undefined)}
export async function completeStudentEnrollment(f:FormData){await requireAdmin();const p=lifecycleBase.safeParse(Object.fromEntries(f));if(!p.success)redirect("/staff/students?error=invalid");const{error}=await(await createClient()).rpc("complete_student_enrollment",{p_student_id:p.data.student_id,p_enrollment_id:p.data.enrollment_id,p_effective_date:p.data.effective_date,p_reason:p.data.reason,p_graduate:f.get("graduate")==="on"});await finishLifecycle(p.data.student_id,f.get("graduate")==="on"?"graduated":"completed",error??undefined)}
export async function deactivateStudent(f:FormData){await requireAdmin();const p=lifecycleBase.safeParse(Object.fromEntries(f));if(!p.success)redirect("/staff/students?error=invalid");const{error}=await(await createClient()).rpc("deactivate_student",{p_student_id:p.data.student_id,p_enrollment_id:p.data.enrollment_id,p_effective_date:p.data.effective_date,p_reason:p.data.reason});await finishLifecycle(p.data.student_id,"deactivated",error??undefined)}
export async function reactivateStudent(f:FormData){await requireAdmin();const p=z.object({student_id:uuid,academic_year_id:uuid,class_id:uuid,academic_section_id:uuid,roll_number:z.string().trim().max(30),enrollment_date:z.string().date(),reason:z.string().trim().max(500),confirm:z.literal("on")}).safeParse(Object.fromEntries(f));if(!p.success)redirect("/staff/students?error=invalid");const{error}=await(await createClient()).rpc("reactivate_student",{p_student_id:p.data.student_id,p_target_academic_year_id:p.data.academic_year_id,p_target_class_id:p.data.class_id,p_target_section_id:p.data.academic_section_id,p_roll_number:p.data.roll_number,p_enrollment_date:p.data.enrollment_date,p_reason:p.data.reason});await finishLifecycle(p.data.student_id,"reactivated",error??undefined)}
