"use client";

import { useState } from "react";

import { archiveEvent, createEvent, updateEvent } from "@/app/staff/actions";
import { StaffActionSubmit } from "@/components/staff-action-submit";

type EventRecord = { id: string; title: string; description: string | null; event_type: "academic" | "exam" | "holiday" | "meeting" | "sports" | "cultural" | "admissions" | "celebration" | "other"; start_at: string; end_at: string | null; location: string | null; status: "draft" | "published" | "archived"; is_public: boolean };
const eventTypes = ["academic", "exam", "holiday", "meeting", "sports", "cultural", "admissions", "celebration", "other"] as const;
const eventTypeLabels: Record<(typeof eventTypes)[number], string> = { academic: "Academic", admissions: "Admissions", celebration: "Celebration", cultural: "Cultural", exam: "Examination", holiday: "Holiday", meeting: "Meeting", other: "Other", sports: "Sports" };

function formatEventDateTimeInput(value: string | null) { if (!value) return ""; const date = new Date(value); if (Number.isNaN(date.getTime())) return ""; const parts = new Intl.DateTimeFormat("en-CA", { day: "2-digit", hour: "2-digit", hour12: false, minute: "2-digit", month: "2-digit", timeZone: "Asia/Kolkata", year: "numeric" }).formatToParts(date); const part = (type: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === type)?.value ?? ""; return `${part("year")}-${part("month")}-${part("day")}T${part("hour")}:${part("minute")}`; }

export function StaffEventForm({ event }: { event?: EventRecord }) {
  const [archiveConfirming, setArchiveConfirming] = useState(false); const editing = Boolean(event); const currentStatus = event?.status ?? "draft"; const action = editing ? updateEvent : createEvent;
  return <div className="staff-event-form-shell"><form className="staff-event-form" action={action}><div className="staff-event-form-grid"><label className="staff-event-wide">Event title<input name="title" required maxLength={180} defaultValue={event?.title ?? ""} /></label><label>Event type<select name="eventType" defaultValue={event?.event_type ?? "other"}>{eventTypes.map((type) => <option key={type} value={type}>{eventTypeLabels[type]}</option>)}</select></label><label>Location <span>Optional</span><input name="location" maxLength={240} defaultValue={event?.location ?? ""} /></label><label>Start date and time <span>IST</span><input name="startAt" required type="datetime-local" defaultValue={formatEventDateTimeInput(event?.start_at ?? null)} /></label><label>End date and time <span>IST · optional</span><input name="endAt" type="datetime-local" defaultValue={formatEventDateTimeInput(event?.end_at ?? null)} /></label><label className="staff-event-wide">Description <span>Optional</span><textarea name="description" rows={8} maxLength={6000} defaultValue={event?.description ?? ""} /></label><label className="staff-event-public"><input name="isPublic" type="checkbox" defaultChecked={event?.is_public ?? true} /><span><strong>Show on the public website</strong><small>Only published public events can appear in Upcoming Events.</small></span></label></div>{editing && <input type="hidden" name="id" value={event?.id ?? ""} />}<div className="staff-event-form-actions">{currentStatus !== "archived" && <><StaffActionSubmit name="status" value="draft" pendingChildren="Saving draft…">Save draft</StaffActionSubmit><StaffActionSubmit name="status" value="published" pendingChildren="Publishing event…">Publish event</StaffActionSubmit></>}</div></form>{editing && event?.status !== "archived" && <aside className="staff-event-archive"><p className="staff-card-label">Archive event</p><p>Remove this event from active staff and public views while preserving its record.</p>{archiveConfirming ? <form action={archiveEvent}><input type="hidden" name="id" value={event?.id ?? ""} /><p className="staff-archive-confirmation">Archive this event? This cannot be undone from this screen.</p><div><button type="button" onClick={() => setArchiveConfirming(false)}>Cancel</button><StaffActionSubmit pendingChildren="Archiving event…">Archive event</StaffActionSubmit></div></form> : <button type="button" onClick={() => setArchiveConfirming(true)}>Archive event</button>}</aside>}</div>;
}
