import { archiveNotice, createNotice, updateNotice } from "@/app/staff/actions";
import { StaffActionSubmit } from "@/components/staff-action-submit";
import { formatNoticeDateTimeInput, noticePriorities, noticePriorityLabels, noticeStatuses, noticeStatusLabels, type Notice } from "@/lib/notices";

export function StaffNoticeForm({ notice }: { notice?: Notice }) {
  const isEditing = Boolean(notice);
  const action = isEditing ? updateNotice : createNotice;
  const noticeId = notice?.id ?? "";

  return <div className="staff-notice-form-shell"><form className="staff-notice-form" action={action}><div className="staff-notice-form-grid"><label className="staff-notice-wide">Title<input name="title" required maxLength={180} defaultValue={notice?.title ?? ""} /></label><label className="staff-notice-wide">Summary <span>Optional</span><textarea name="summary" rows={3} maxLength={400} defaultValue={notice?.summary ?? ""} /></label><label className="staff-notice-wide">Content<textarea name="content" required rows={10} maxLength={6000} defaultValue={notice?.content ?? ""} /></label><label>Priority<select name="priority" defaultValue={notice?.priority ?? "normal"}>{noticePriorities.map((priority) => <option key={priority} value={priority}>{noticePriorityLabels[priority]}</option>)}</select></label><label>Status<select name="status" defaultValue={notice?.status ?? "draft"}>{noticeStatuses.map((status) => <option key={status} value={status}>{noticeStatusLabels[status]}</option>)}</select></label><label>Publish date and time <span>IST · optional</span><input name="publishedAt" type="datetime-local" defaultValue={formatNoticeDateTimeInput(notice?.published_at ?? null)} /></label><label>Expiry date and time <span>IST · optional</span><input name="expiresAt" type="datetime-local" defaultValue={formatNoticeDateTimeInput(notice?.expires_at ?? null)} /></label></div>{isEditing && <input type="hidden" name="id" value={noticeId} />}<div className="staff-notice-form-actions"><StaffActionSubmit pendingChildren={isEditing ? "Saving changes…" : "Creating notice…"}>{isEditing ? "Save changes" : "Create notice"}</StaffActionSubmit></div></form>{isEditing && notice?.status !== "archived" && <form className="staff-notice-archive" action={archiveNotice}><input type="hidden" name="id" value={noticeId} /><StaffActionSubmit pendingChildren="Archiving notice…">Archive notice</StaffActionSubmit><p>Archiving removes this notice from the public website without deleting its record.</p></form>}</div>;
}
