import type { ReactNode } from "react";
import type { Student } from "@/lib/students";
import type { StudentFieldErrors } from "@/lib/student-validation";

const text = (student: Student, name: keyof Student) => String(student[name] ?? "");
type PersonalFieldProps = {
  student: Student;
  name: keyof Student;
  label: string;
  type?: "date" | "email" | "tel" | "text";
  required?: boolean;
  inputMode?: "numeric";
  maxLength?: number;
  submittedValues?: Record<string, FormDataEntryValue | undefined>;
  fieldErrors?: StudentFieldErrors;
};

const submittedValue = (student: Student, name: keyof Student, submittedValues?: Record<string, FormDataEntryValue | undefined>) => {
  const value = submittedValues?.[name];
  return typeof value === "string" ? value : text(student, name);
};

function PersonalInput({ student, name, label, type = "text", required, inputMode, maxLength, submittedValues, fieldErrors }: PersonalFieldProps) {
  const error = fieldErrors?.[name]?.[0];
  const id = `student-${name}`;
  return <label className={error ? "student-field-error" : undefined} htmlFor={id}>{label}{required ? " *" : ""}<input aria-describedby={error ? `${id}-error` : undefined} aria-invalid={Boolean(error)} defaultValue={submittedValue(student, name, submittedValues)} id={id} inputMode={inputMode} maxLength={maxLength} name={name} required={required} type={type}/>{error ? <span className="student-field-message" id={`${id}-error`}>{error}</span> : null}</label>;
}

function PersonalSelect({ student, name, label, children, required, submittedValues, fieldErrors }: Omit<PersonalFieldProps, "type" | "inputMode" | "maxLength"> & { children: ReactNode }) {
  const error = fieldErrors?.[name]?.[0];
  const id = `student-${name}`;
  return <label className={error ? "student-field-error" : undefined} htmlFor={id}>{label}{required ? " *" : ""}<select aria-describedby={error ? `${id}-error` : undefined} aria-invalid={Boolean(error)} defaultValue={submittedValue(student, name, submittedValues)} id={id} name={name} required={required}>{children}</select>{error ? <span className="student-field-message" id={`${id}-error`}>{error}</span> : null}</label>;
}

function TransportRequired({ student, submittedValues, fieldErrors }: Pick<PersonalFieldProps, "student" | "submittedValues" | "fieldErrors">) {
  const name = "transport_required";
  const error = fieldErrors?.[name]?.[0];
  const id = `student-${name}`;
  const submitted = submittedValues?.[name];
  const checked = typeof submitted === "string" ? submitted === "on" : Boolean(student.transport_required);
  return <label className={error ? "student-field-error" : undefined} htmlFor={id}>Transport required<input aria-describedby={error ? `${id}-error` : undefined} aria-invalid={Boolean(error)} defaultChecked={checked} id={id} name={name} type="checkbox"/>{error ? <span className="student-field-message" id={`${id}-error`}>{error}</span> : null}</label>;
}

export function StudentEditFields({ student, submittedValues, fieldErrors }: { student: Student; submittedValues?: Record<string, FormDataEntryValue | undefined>; fieldErrors?: StudentFieldErrors }) {
  const s = student;
  return <>
    <section className="student-form-section"><header><p className="academic-kicker">Personal information</p><h2>Student information</h2></header><div className="student-form-grid"><PersonalInput student={s} name="full_name" label="Student name" required submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="admission_number" label="Admission number" required submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="preferred_name" label="Preferred name" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="date_of_birth" label="Date of birth" type="date" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalSelect student={s} name="gender" label="Gender" submittedValues={submittedValues} fieldErrors={fieldErrors}><option value="">Not specified</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option><option value="not_specified">Prefer not to say</option></PersonalSelect><PersonalSelect student={s} name="blood_group" label="Blood group" submittedValues={submittedValues} fieldErrors={fieldErrors}><option value="">Not specified</option><option value="a_positive">A+</option><option value="a_negative">A−</option><option value="b_positive">B+</option><option value="b_negative">B−</option><option value="ab_positive">AB+</option><option value="ab_negative">AB−</option><option value="o_positive">O+</option><option value="o_negative">O−</option><option value="unknown">Unknown</option></PersonalSelect><PersonalInput student={s} name="student_category" label="Student category" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="aadhaar_number" label="Aadhaar number" inputMode="numeric" maxLength={12} submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="nationality" label="Nationality" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="mother_tongue" label="Mother tongue" submittedValues={submittedValues} fieldErrors={fieldErrors}/></div></section>
    <section className="student-form-section"><header><p className="academic-kicker">Admission information</p><h2>Admission</h2></header><div className="student-form-grid"><PersonalInput student={s} name="admission_date" label="Admission date" type="date" required submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalSelect student={s} name="status" label="Status" required submittedValues={submittedValues} fieldErrors={fieldErrors}><option value="active">Active</option><option value="inactive">Inactive</option><option value="graduated">Graduated</option><option value="transferred">Transferred</option></PersonalSelect><PersonalInput student={s} name="previous_school_name" label="Previous school name" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="previous_class" label="Previous class" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="previous_school_tc_number" label="Previous school TC number" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="previous_school_location" label="Previous school location" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="admission_remarks" label="Remarks" submittedValues={submittedValues} fieldErrors={fieldErrors}/></div></section>
    <section className="student-form-section"><header><p className="academic-kicker">Parent / guardian information</p><h2>Contacts</h2></header><div className="student-form-grid"><PersonalInput student={s} name="father_name" label="Father name" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="father_mobile" label="Father mobile" type="tel" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="father_email" label="Father email" type="email" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="father_occupation" label="Father occupation" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="mother_name" label="Mother name" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="mother_mobile" label="Mother mobile" type="tel" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="mother_email" label="Mother email" type="email" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="mother_occupation" label="Mother occupation" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="guardian_name" label="Guardian name" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="guardian_relationship" label="Guardian relationship" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="guardian_mobile" label="Guardian mobile" type="tel" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="guardian_email" label="Guardian email" type="email" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="emergency_contact_name" label="Emergency contact name" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="emergency_contact_relationship" label="Emergency contact relationship" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="emergency_contact_mobile" label="Emergency contact mobile" type="tel" submittedValues={submittedValues} fieldErrors={fieldErrors}/></div></section>
    <section className="student-form-section"><header><p className="academic-kicker">Address</p><h2>Residence</h2></header><div className="student-form-grid"><PersonalInput student={s} name="door_number" label="Door / house no." submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="street" label="Street" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="address_line_2" label="Address line 2" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="area_locality" label="Area / locality" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="village_town_city" label="Village / town / city" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="mandal" label="Mandal" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="district" label="District" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="state" label="State" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="postal_code" label="Postal code" submittedValues={submittedValues} fieldErrors={fieldErrors}/></div></section>
    <section className="student-form-section"><header><p className="academic-kicker">Additional information</p><h2>School details</h2></header><div className="student-form-grid"><PersonalInput student={s} name="identification_mark_1" label="Identification mark 1" submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="identification_mark_2" label="Identification mark 2" submittedValues={submittedValues} fieldErrors={fieldErrors}/><TransportRequired student={s} submittedValues={submittedValues} fieldErrors={fieldErrors}/><PersonalInput student={s} name="general_notes" label="General notes" submittedValues={submittedValues} fieldErrors={fieldErrors}/></div></section>
  </>;
}
