import type { Student } from "@/lib/students";

type Profile = Student & Record<string, string | boolean | null | undefined>;
const text = (student: Profile, name: string) => String(student[name] ?? "");
const Input = ({ student, name, label, type = "text" }: { student: Profile; name: string; label: string; type?: string }) => <label>{label}<input name={name} type={type} defaultValue={text(student, name)} /></label>;

export function StudentEditFields({ student }: { student: Student }) {
  const s = student as Profile;
  return <>
    <section className="student-form-section"><header><p className="academic-kicker">Personal information</p><h2>Student information</h2></header><div className="student-form-grid"><Input student={s} name="full_name" label="Student name *"/><Input student={s} name="admission_number" label="Admission number *"/><Input student={s} name="preferred_name" label="Preferred name"/><Input student={s} name="date_of_birth" label="Date of birth" type="date"/><label>Gender<select name="gender" defaultValue={text(s,"gender")}><option value="">Not specified</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option><option value="not_specified">Prefer not to say</option></select></label><Input student={s} name="blood_group" label="Blood group"/><Input student={s} name="student_category" label="Student category"/><Input student={s} name="aadhaar_number" label="Aadhaar number"/><Input student={s} name="nationality" label="Nationality"/><Input student={s} name="mother_tongue" label="Mother tongue"/></div></section>
    <section className="student-form-section"><header><p className="academic-kicker">Admission information</p><h2>Admission</h2></header><div className="student-form-grid"><Input student={s} name="admission_date" label="Admission date *" type="date"/><label>Status<select name="status" defaultValue={text(s,"status")}><option value="active">Active</option><option value="inactive">Inactive</option><option value="graduated">Graduated</option><option value="transferred">Transferred</option></select></label><Input student={s} name="previous_school_name" label="Previous school"/><Input student={s} name="previous_class" label="Previous class"/><Input student={s} name="previous_school_tc_number" label="TC number"/><Input student={s} name="previous_school_location" label="Previous school location"/><Input student={s} name="admission_remarks" label="Remarks"/></div></section>
    <section className="student-form-section"><header><p className="academic-kicker">Parent / guardian information</p><h2>Contacts</h2></header><div className="student-form-grid">{[["father_name","Father name"],["father_mobile","Father mobile"],["father_email","Father email"],["father_occupation","Father occupation"],["mother_name","Mother name"],["mother_mobile","Mother mobile"],["mother_email","Mother email"],["mother_occupation","Mother occupation"],["guardian_name","Guardian name"],["guardian_relationship","Guardian relationship"],["guardian_mobile","Guardian mobile"],["guardian_email","Guardian email"],["emergency_contact_name","Emergency contact"],["emergency_contact_relationship","Emergency relationship"],["emergency_contact_mobile","Emergency mobile"]].map(([name,label])=><Input key={name} student={s} name={name} label={label} type={name.includes("email")?"email":"text"}/>)}</div></section>
    <section className="student-form-section"><header><p className="academic-kicker">Address</p><h2>Residence</h2></header><div className="student-form-grid">{[["door_number","Door / house no."],["street","Street"],["address_line_2","Address line 2"],["area_locality","Area / locality"],["village_town_city","Village / town / city"],["mandal","Mandal"],["district","District"],["state","State"],["postal_code","Postal code"]].map(([name,label])=><Input key={name} student={s} name={name} label={label}/>)}</div></section>
    <section className="student-form-section"><header><p className="academic-kicker">Additional information</p><h2>School details</h2></header><div className="student-form-grid"><Input student={s} name="identification_mark_1" label="Identification mark 1"/><Input student={s} name="identification_mark_2" label="Identification mark 2"/><label>Transport required<input name="transport_required" type="checkbox" defaultChecked={Boolean(s.transport_required)}/></label><Input student={s} name="general_notes" label="General notes"/></div></section>
  </>;
}
