import "server-only";

import { z } from "zod";

import { requireStaff } from "@/lib/staff/auth";
import { createClient } from "@/lib/supabase/server";

export const galleryStatuses = ["draft", "published", "archived"] as const;
export const galleryStatusSchema = z.enum(galleryStatuses);
export type GalleryStatus = z.infer<typeof galleryStatusSchema>;
export const galleryStatusLabels: Record<GalleryStatus, string> = { archived: "Archived", draft: "Draft", published: "Published" };
export type GalleryAlbum = { id: string; title: string; description: string | null; event_date: string | null; cover_image_path: string | null; status: GalleryStatus; is_public: boolean; created_at: string; updated_at: string; image_count?: number };
export type GalleryImage = { id: string; album_id: string; storage_path: string; caption: string | null; alt_text: string; display_order: number; created_at: string; signed_url?: string };
const albumFields = "id, title, description, event_date, cover_image_path, status, is_public, created_at, updated_at";
const imageFields = "id, album_id, storage_path, caption, alt_text, display_order, created_at";
function date(value: string | null) { const parsed = value ? new Date(`${value}T00:00:00+05:30`) : null; return parsed && !Number.isNaN(parsed.getTime()) ? parsed : null; }
function log(operation: string, error: { code?: string; details?: string; hint?: string; message?: string }) { console.error(operation, { category: "database-query", code: error.code, details: error.details, hint: error.hint, message: error.message }); }
export function formatGalleryDate(value: string | null) { const parsed = date(value); return parsed ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeZone: "Asia/Kolkata" }).format(parsed) : "No date set"; }
async function signed(images: GalleryImage[]) { if (!images.length) return images; const supabase = await createClient(); const { data, error } = await supabase.storage.from("gallery-media").createSignedUrls(images.map((image) => image.storage_path), 3600); if (error) { log("Gallery signed URL creation failed.", error); return images; } return images.map((image, index) => ({ ...image, signed_url: data[index]?.signedUrl })); }

export async function getStaffGallery(filters: { q?: string; status?: string }) { await requireStaff(); const supabase = await createClient(); let query = supabase.from("gallery_albums").select(`${albumFields}, gallery_images(count)`).order("updated_at", { ascending: false }).limit(100); const queryText = filters.q?.trim().slice(0, 100); const status = galleryStatusSchema.safeParse(filters.status); if (queryText) query = query.ilike("title", `%${queryText.replace(/[%,_]/g, "\\$&")}%`); if (status.success) query = query.eq("status", status.data); const [list, total] = await Promise.all([query, supabase.from("gallery_albums").select("id", { count: "exact", head: true })]); if (list.error || total.error) { log("Staff gallery list failed.", list.error ?? total.error!); return { albums: [] as GalleryAlbum[], failed: true, total: 0 }; } return { albums: (list.data ?? []).map((album) => ({ ...(album as GalleryAlbum), image_count: (album.gallery_images as unknown as { count: number }[])?.[0]?.count ?? 0 })), failed: false, total: total.count ?? 0 }; }
export async function getStaffGalleryAlbum(id: string) { await requireStaff(); if (!z.string().uuid().safeParse(id).success) return null; const supabase = await createClient(); const [albumResult, imagesResult] = await Promise.all([supabase.from("gallery_albums").select(albumFields).eq("id", id).maybeSingle(), supabase.from("gallery_images").select(imageFields).eq("album_id", id).order("display_order").order("created_at")]); if (albumResult.error || imagesResult.error) { log("Staff gallery detail failed.", albumResult.error ?? imagesResult.error!); return null; } return { album: albumResult.data as GalleryAlbum, images: await signed((imagesResult.data ?? []) as GalleryImage[]) }; }
export async function getStaffGalleryOverview() { await requireStaff(); const supabase = await createClient(); const [published, drafts, latest] = await Promise.all([supabase.from("gallery_albums").select("id", { count: "exact", head: true }).eq("status", "published"), supabase.from("gallery_albums").select("id", { count: "exact", head: true }).eq("status", "draft"), supabase.from("gallery_albums").select("id, title, updated_at").order("updated_at", { ascending: false }).limit(1).maybeSingle()]); return { drafts: drafts.count ?? 0, latest: latest.data as Pick<GalleryAlbum, "id" | "title" | "updated_at"> | null, published: published.count ?? 0 }; }
export async function getPublicGallery() { const supabase = await createClient(); const { data, error } = await supabase.from("gallery_albums").select(`${albumFields}, gallery_images(${imageFields})`).eq("status", "published").eq("is_public", true).order("event_date", { ascending: false, nullsFirst: false }).limit(24); if (error) { log("Public gallery list failed.", error); return [] as Array<GalleryAlbum & { cover?: GalleryImage }>; } const albums = (data ?? []).map((album) => { const images = (album.gallery_images ?? []) as GalleryImage[]; const cover = images.find((image) => image.storage_path === album.cover_image_path) ?? images[0]; return { ...(album as GalleryAlbum), cover }; }); const covers = await signed(albums.flatMap((album) => album.cover ? [album.cover] : [])); return albums.map((album) => ({ ...album, cover: covers.find((image) => image.id === album.cover?.id) })); }
export async function getPublicGalleryAlbum(id: string) { if (!z.string().uuid().safeParse(id).success) return null; const supabase = await createClient(); const album = await supabase.from("gallery_albums").select(albumFields).eq("id", id).eq("status", "published").eq("is_public", true).maybeSingle(); if (album.error || !album.data) return null; const images = await supabase.from("gallery_images").select(imageFields).eq("album_id", id).order("display_order").order("created_at").limit(60); if (images.error) { log("Public gallery album failed.", images.error); return null; } return { album: album.data as GalleryAlbum, images: await signed((images.data ?? []) as GalleryImage[]) }; }
