import "server-only";
import { z } from "zod";
import { requireAdmin } from "@/lib/staff/auth";
import { createClient } from "@/lib/supabase/server";

export type Student = { id:string; admission_number:string; full_name:string; preferred_name:string|null; date_of_birth:string|null; gender:string|null; blood_group:string|null; student_category:string|null; aadhaar_number:string|null; nationality:string|null; mother_tongue:string|null; father_guardian_name:string|null; mother_name:string|null; primary_phone:string|null; secondary_phone:string|null; email:string|null; address_line_1:string|null; address_line_2:string|null; locality:string|null; city:string|null; state:string|null; postal_code:string|null; door_number:string|null; street:string|null; area_locality:string|null; village_town_city:string|null; mandal:string|null; district:string|null; father_name:string|null; father_mobile:string|null; father_email:string|null; father_occupation:string|null; mother_mobile:string|null; mother_email:string|null; mother_occupation:string|null; guardian_name:string|null; guardian_relationship:string|null; guardian_mobile:string|null; guardian_email:string|null; primary_contact:"father"|"mother"|"guardian"|null; emergency_contact_name:string|null; emergency_contact_relationship:string|null; emergency_contact_mobile:string|null; previous_school_name:string|null; previous_class:string|null; previous_school_tc_number:string|null; previous_school_location:string|null; admission_remarks:string|null; identification_mark_1:string|null; identification_mark_2:string|null; transport_required:boolean; general_notes:string|null; profile_photo_path:string|null; admission_date:string; status:"active"|"inactive"|"graduated"|"transferred" };
export type Enrollment = { id:string; student_id:string; academic_year_id:string; class_id:string; academic_section_id:string; roll_number:string|null; status:"active"|"inactive"|"completed"|"transferred"; enrollment_date:string };
export type StudentAcademicData = { years:{id:string;label:string;status:string}[]; classes:{id:string;name:string;active:boolean}[]; sections:{id:string;name:string;academic_year_id:string;class_id:string;active:boolean}[] };
export type DirectoryStudent = Pick<Student,"id"|"admission_number"|"full_name"|"gender"|"date_of_birth"|"status">;
const studentDetailFields="id,admission_number,full_name,preferred_name,date_of_birth,gender,blood_group,student_category,aadhaar_number,nationality,mother_tongue,father_guardian_name,mother_name,primary_phone,secondary_phone,email,address_line_1,address_line_2,locality,city,state,postal_code,door_number,street,area_locality,village_town_city,mandal,district,father_name,father_mobile,father_email,father_occupation,mother_mobile,mother_email,mother_occupation,guardian_name,guardian_relationship,guardian_mobile,guardian_email,primary_contact,emergency_contact_name,emergency_contact_relationship,emergency_contact_mobile,previous_school_name,previous_class,previous_school_tc_number,previous_school_location,admission_remarks,identification_mark_1,identification_mark_2,transport_required,general_notes,profile_photo_path,admission_date,status";

function queryFailure(operation:string,error:{code?:string;message?:string;details?:string;hint?:string}){console.error("Student data query failed.",{operation,code:error.code,message:error.message,details:error.details,hint:error.hint});throw new Error("Student data is temporarily unavailable.")}

export async function studentFormData(){await requireAdmin();const s=await createClient();const [years,classes,sections]=await Promise.all([s.from("academic_years").select("id,label,status").order("start_date",{ascending:false}).limit(30),s.from("school_classes").select("id,name,active").order("display_order").limit(30),s.from("academic_sections").select("id,name,academic_year_id,class_id,active").limit(300)]);const failed=years.error??classes.error??sections.error;if(failed)queryFailure("studentFormData",failed);return{years:years.data??[],classes:classes.data??[],sections:sections.data??[]} as StudentAcademicData;}

export async function studentData(){await requireAdmin();const s=await createClient();const [students,enrollments,years,classes,sections]=await Promise.all([s.from("students").select("id,admission_number,full_name,gender,date_of_birth,status").order("full_name").limit(500),s.from("student_enrollments").select("id,student_id,academic_year_id,class_id,academic_section_id,roll_number,status,enrollment_date").limit(1000),s.from("academic_years").select("id,label,status").order("start_date",{ascending:false}).limit(30),s.from("school_classes").select("id,name,active").order("display_order").limit(30),s.from("academic_sections").select("id,name,academic_year_id,class_id,active").limit(300)]);const failed=students.error??enrollments.error??years.error??classes.error??sections.error;if(failed)queryFailure("studentData",failed);return{students:(students.data??[]) as DirectoryStudent[],enrollments:(enrollments.data??[]) as Enrollment[],years:years.data??[],classes:classes.data??[],sections:sections.data??[]} as {students:DirectoryStudent[];enrollments:Enrollment[]} & StudentAcademicData;}

export async function studentDetail(id:string){await requireAdmin();if(!z.string().uuid().safeParse(id).success)return{student:null,enrollments:[],years:[],classes:[],sections:[]} as {student:Student|null;enrollments:Enrollment[]} & StudentAcademicData;const s=await createClient();const [student,enrollments,years,classes,sections]=await Promise.all([s.from("students").select(studentDetailFields).eq("id",id).maybeSingle(),s.from("student_enrollments").select("id,student_id,academic_year_id,class_id,academic_section_id,roll_number,status,enrollment_date").eq("student_id",id).order("enrollment_date",{ascending:false}).order("created_at",{ascending:false}),s.from("academic_years").select("id,label,status").order("start_date",{ascending:false}).limit(30),s.from("school_classes").select("id,name,active").order("display_order").limit(30),s.from("academic_sections").select("id,name,academic_year_id,class_id,active").limit(300)]);const failed=student.error??enrollments.error??years.error??classes.error??sections.error;if(failed)queryFailure("studentDetail",failed);return{student:student.data as Student|null,enrollments:(enrollments.data??[]) as Enrollment[],years:years.data??[],classes:classes.data??[],sections:sections.data??[]} as {student:Student|null;enrollments:Enrollment[]} & StudentAcademicData;}
