"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdmin } from "@/lib/staff/auth";
import { createClient } from "@/lib/supabase/server";

const uuid = z.string().uuid();
const back = (path: string) => { revalidatePath("/staff"); revalidatePath("/staff/academics"); revalidatePath(path); };
export async function saveYear(f: FormData) { await requireAdmin(); const p = z.object({ label: z.string().trim().min(4).max(30), start_date: z.string().date(), end_date: z.string().date(), status: z.enum(["planning", "current", "closed"]) }).safeParse(Object.fromEntries(f)); if (!p.success || p.data.end_date <= p.data.start_date) redirect("/staff/academics/years?error=invalid"); const s = await createClient(); if (p.data.status === "current") await s.from("academic_years").update({ status: "planning" }).eq("status", "current"); const { error } = await s.from("academic_years").insert(p.data); if (error) redirect("/staff/academics/years?error=save"); back("/staff/academics/years"); redirect("/staff/academics/years?created=1"); }
export async function saveSection(f: FormData) { await requireAdmin(); const p = z.object({ academic_year_id: uuid, class_id: uuid, name: z.string().trim().min(1).max(20), class_teacher_id: z.union([uuid, z.literal("")]) }).safeParse(Object.fromEntries(f)); if (!p.success) redirect("/staff/academics/sections?error=invalid"); const { error } = await (await createClient()).from("academic_sections").insert({ ...p.data, class_teacher_id: p.data.class_teacher_id || null }); if (error) { console.error("Academic section creation failed.", { operation: "createAcademicSection", code: error.code, message: error.message, details: error.details, hint: error.hint }); redirect("/staff/academics/sections?error=save"); } back("/staff/academics/sections"); redirect("/staff/academics/sections?created=1"); }
export async function saveSubject(f: FormData) { await requireAdmin(); const p = z.object({ name: z.string().trim().min(1).max(100), code: z.string().trim().max(20), display_order: z.coerce.number().int().min(0).max(10000) }).safeParse(Object.fromEntries(f)); if (!p.success) redirect("/staff/academics/subjects?error=invalid"); const { error } = await (await createClient()).from("subjects").insert({ ...p.data, code: p.data.code || null }); if (error) redirect("/staff/academics/subjects?error=save"); back("/staff/academics/subjects"); redirect("/staff/academics/subjects?created=1"); }
export async function saveAssignment(f: FormData) { await requireAdmin(); const p = z.object({ academic_section_id: uuid, subject_id: uuid, teacher_id: z.union([uuid, z.literal("")]) }).safeParse(Object.fromEntries(f)); if (!p.success) redirect("/staff/academics/assignments?error=invalid"); const { error } = await (await createClient()).from("section_subject_assignments").insert({ ...p.data, teacher_id: p.data.teacher_id || null }); if (error) redirect("/staff/academics/assignments?error=save"); back("/staff/academics/assignments"); redirect("/staff/academics/assignments?created=1"); }
export async function toggleClass(f: FormData) { await requireAdmin(); const id = uuid.safeParse(f.get("id")); const active = f.get("active") === "true"; if (!id.success) redirect("/staff/academics/classes"); await (await createClient()).from("school_classes").update({ active }).eq("id", id.data); back("/staff/academics/classes"); redirect("/staff/academics/classes?updated=1"); }
