import Link from "next/link";

import { eventTypeLabels, getStaffEventsOverview } from "@/lib/events";
import { getStaffFacultyOverview } from "@/lib/faculty";
import { getStaffGalleryOverview } from "@/lib/gallery";
import { getStaffNoticesOverview } from "@/lib/notices";
import { admissionStatusLabels, formatAdmissionDate, formatAdmissionTime, getStaffDashboardOverview } from "@/lib/staff/admissions";

export default async function StaffDashboardPage() {
  const [{ attention, metrics, recent }, notices, events, gallery, faculty] = await Promise.all([getStaffDashboardOverview(), getStaffNoticesOverview(), getStaffEventsOverview(), getStaffGalleryOverview(), getStaffFacultyOverview()]);
  return <><header className="staff-page-header staff-dashboard-header"><div><p className="eyebrow">Staff Portal</p><h1>Dashboard</h1><p>Overview of admissions activity and school operations.</p></div></header><section className="staff-dashboard-metrics" aria-label="Admissions overview"><article className="staff-dashboard-metric staff-dashboard-metric-primary"><span>Total enquiries</span><strong>{metrics.total}</strong></article><article className="staff-dashboard-metric"><span>New</span><strong>{metrics.new}</strong></article><article className="staff-dashboard-metric"><span>Follow-up</span><strong>{metrics.follow_up}</strong></article><article className="staff-dashboard-metric"><span>Admitted</span><strong>{metrics.admitted}</strong></article></section><div className="staff-dashboard-sections"><DashboardList heading="Needs attention" href="/staff/admissions" items={attention} empty="There are no new or follow-up enquiries requiring attention."/><DashboardList heading="Recent enquiries" href="/staff/admissions" items={recent} empty="New admission enquiries will appear here as they are received."/></div><div className="staff-dashboard-modules"><Module title="Admissions" kicker="Portal module" href="/staff/admissions" action="Open Admissions">Manage parent enquiries and admission follow-ups from one focused workspace.</Module><Module title="Notices" kicker="Communication" href="/staff/notices" action="Manage notices"><strong>{notices.published}</strong> published · <strong>{notices.drafts}</strong> draft{notices.drafts === 1 ? "" : "s"}{notices.recent && <> · Latest: {notices.recent.title}</>}</Module><Module title="Events" kicker="School calendar" href="/staff/events" action="Manage events"><strong>{events.upcoming}</strong> upcoming event{events.upcoming === 1 ? "" : "s"}{events.next && <> · Next: {events.next.title} ({eventTypeLabels[events.next.event_type]})</>}</Module><Module title="Gallery" kicker="School media" href="/staff/gallery" action="Manage Gallery"><strong>{gallery.published}</strong> published · <strong>{gallery.drafts}</strong> draft{gallery.drafts === 1 ? "" : "s"}{gallery.latest && <> · Latest: {gallery.latest.title}</>}</Module><Module title="Faculty" kicker="School community" href="/staff/faculty" action="Manage faculty"><strong>{faculty.active}</strong> active · <strong>{faculty.public}</strong> public profile{faculty.public === 1 ? "" : "s"}{faculty.latest && <> · Latest: {faculty.latest.full_name}</>}</Module></div></>;
}

function DashboardList({ heading, href, items, empty }: { heading: string; href: string; items: Awaited<ReturnType<typeof getStaffDashboardOverview>>["attention"]; empty: string }) { return <section className="staff-dashboard-section"><header><div><p className="staff-dashboard-section-kicker">Admissions</p><h2>{heading}</h2></div><Link href={href}>View all enquiries <span aria-hidden="true">→</span></Link></header>{items.length ? <ul className="staff-dashboard-list">{items.map((enquiry) => <li key={enquiry.id}><Link href={`/staff/admissions/${enquiry.id}`}><span className="staff-dashboard-person"><strong>{enquiry.student_name}</strong><span>{enquiry.guardian_name} · {enquiry.class_seeking}</span></span><span className="staff-dashboard-meta"><span className={`status-badge status-${enquiry.status}`}>{admissionStatusLabels[enquiry.status]}</span><time dateTime={enquiry.created_at}>{formatAdmissionDate(enquiry.created_at)} · {formatAdmissionTime(enquiry.created_at)}</time></span></Link></li>)}</ul> : <p className="staff-dashboard-empty">{empty}</p>}</section>; }
function Module({ title, kicker, href, action, children }: { title: string; kicker: string; href: string; action: string; children: React.ReactNode }) { return <section className="staff-dashboard-module"><header><p className="staff-dashboard-section-kicker">{kicker}</p><h2>{title}</h2><p>{children}</p></header><Link href={href}>{action} <span aria-hidden="true">→</span></Link></section>; }
