"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";

import { facultyDepartmentSchema } from "@/lib/faculty";
import { requireStaff } from "@/lib/staff/auth";
import { createClient } from "@/lib/supabase/server";

export type FacultyFormState = { formError?: string; fieldErrors?: Partial<Record<"full_name" | "designation" | "department" | "qualification" | "bio" | "display_order" | "photo", string>> };
const imageTypes = new Set(["image/jpeg", "image/png", "image/webp"]);
const facultySchema = z.object({ id: z.string().uuid().optional(), full_name: z.string().trim().min(1, "Enter the staff member’s full name.").max(140), designation: z.string().trim().min(1, "Enter a designation or job title.").max(140), department: facultyDepartmentSchema, qualification: z.string().trim().max(240), bio: z.string().trim().max(1600), display_order: z.coerce.number().int().min(0).max(10000), is_public: z.boolean() });
function invalid(result: z.ZodSafeParseError<unknown>): FacultyFormState { const fieldErrors: FacultyFormState["fieldErrors"] = {}; for (const issue of result.error.issues) { const key = issue.path[0]; if (typeof key === "string" && key in { full_name: 1, designation: 1, department: 1, qualification: 1, bio: 1, display_order: 1 }) fieldErrors[key as keyof NonNullable<FacultyFormState["fieldErrors"]>] = issue.message; } return { formError: "Please review the highlighted fields.", fieldErrors }; }
function pathFor(file: File) { const extension = file.type === "image/jpeg" ? "jpg" : file.type === "image/png" ? "png" : "webp"; return `${crypto.randomUUID()}.${extension}`; }
function revalidateFaculty() { revalidatePath("/faculty"); revalidatePath("/staff"); revalidatePath("/staff/faculty"); }
async function save(formData: FormData, editing: boolean): Promise<FacultyFormState> { await requireStaff(); const parsed = facultySchema.safeParse({ id: formData.get("id") || undefined, full_name: formData.get("full_name"), designation: formData.get("designation"), department: formData.get("department"), qualification: formData.get("qualification"), bio: formData.get("bio"), display_order: formData.get("display_order"), is_public: formData.get("is_public") === "on" }); if (!parsed.success) return invalid(parsed); const photo = formData.get("photo"); if (photo instanceof File && photo.size && (!imageTypes.has(photo.type) || photo.size > 4194304)) return { formError: "The profile photo must be a JPEG, PNG or WebP image up to 4 MB.", fieldErrors: { photo: "Choose a supported image up to 4 MB." } }; if (editing && !parsed.data.id) return { formError: "We could not find this faculty record." }; const supabase = await createClient(); let newPath: string | null = null; if (photo instanceof File && photo.size) { newPath = pathFor(photo); const { error } = await supabase.storage.from("faculty-photos").upload(newPath, photo, { contentType: photo.type, upsert: false }); if (error) return { formError: "We could not upload the profile photo. Please try again." }; }
  const base = { full_name: parsed.data.full_name, designation: parsed.data.designation, department: parsed.data.department, qualification: parsed.data.qualification || null, bio: parsed.data.bio || null, display_order: parsed.data.display_order, is_public: parsed.data.is_public };
  if (!editing) { const { data, error } = await supabase.from("faculty_members").insert({ ...base, photo_path: newPath }).select("id").single(); if (error || !data) { if (newPath) await supabase.storage.from("faculty-photos").remove([newPath]); return { formError: "We could not save this faculty record. Please try again." }; } revalidateFaculty(); redirect(`/staff/faculty/${data.id}/edit?created=1`); }
  const { data: current } = await supabase.from("faculty_members").select("photo_path").eq("id", parsed.data.id!).maybeSingle(); const removePhoto = formData.get("remove_photo") === "on"; const photo_path = newPath ?? (removePhoto ? null : current?.photo_path ?? null); const { error } = await supabase.from("faculty_members").update({ ...base, photo_path }).eq("id", parsed.data.id!); if (error) { if (newPath) await supabase.storage.from("faculty-photos").remove([newPath]); return { formError: "We could not save this faculty record. Please try again." }; } if ((newPath || removePhoto) && current?.photo_path) await supabase.storage.from("faculty-photos").remove([current.photo_path]); revalidateFaculty(); redirect(`/staff/faculty/${parsed.data.id}/edit?updated=1`);
}
export async function createFacultyMember(_: FacultyFormState, formData: FormData) { return save(formData, false); }
export async function updateFacultyMember(_: FacultyFormState, formData: FormData) { return save(formData, true); }
export async function archiveFacultyMember(formData: FormData) { await requireStaff(); const id = z.string().uuid().safeParse(formData.get("id")); if (!id.success) redirect("/staff/faculty"); await (await createClient()).from("faculty_members").update({ status: "archived", is_public: false }).eq("id", id.data); revalidateFaculty(); redirect(`/staff/faculty/${id.data}/edit?archived=1`); }
