do $$ begin create type public.document_status as enum ('draft','published','archived'); exception when duplicate_object then null; end $$;
do $$ begin create type public.document_category as enum ('admissions','academic','calendar','circular','fees','policy','syllabus','examination','other'); exception when duplicate_object then null; end $$;
create table public.school_documents (id uuid primary key default gen_random_uuid(),title text not null check(char_length(title) between 1 and 180),description text check(description is null or char_length(description)<=2000),category public.document_category not null default 'other',academic_year text check(academic_year is null or char_length(academic_year)<=30),storage_path text not null unique,original_filename text not null,file_size bigint not null check(file_size>0 and file_size<=10485760),mime_type text not null,status public.document_status not null default 'draft',is_public boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id) on delete set null,updated_by uuid references auth.users(id) on delete set null);
create index school_documents_staff_idx on public.school_documents(status,updated_at desc);create index school_documents_public_idx on public.school_documents(category,updated_at desc) where status='published' and is_public=true;
create or replace function public.set_school_document_audit_fields() returns trigger language plpgsql security invoker set search_path=public as $$ begin if tg_op='INSERT' then new.created_by=auth.uid();end if;new.updated_by=auth.uid();new.updated_at=now();return new;end;$$;create trigger set_school_document_audit_fields before insert or update on public.school_documents for each row execute function public.set_school_document_audit_fields();
alter table public.school_documents enable row level security;revoke all on public.school_documents from anon,authenticated;grant select on public.school_documents to anon;grant select,insert,update on public.school_documents to authenticated;
create policy "Public can read published documents" on public.school_documents for select to anon,authenticated using(status='published' and is_public=true);create policy "Active staff can read documents" on public.school_documents for select to authenticated using(public.is_active_staff());create policy "Active staff can create documents" on public.school_documents for insert to authenticated with check(public.is_active_staff());create policy "Active staff can update documents" on public.school_documents for update to authenticated using(public.is_active_staff()) with check(public.is_active_staff());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('school-documents','school-documents',false,10485760,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']) on conflict(id) do nothing;
create policy "Public can read eligible documents" on storage.objects for select to anon,authenticated using(bucket_id='school-documents' and exists(select 1 from public.school_documents d where d.storage_path=name and d.status='published' and d.is_public=true));create policy "Active staff can read documents" on storage.objects for select to authenticated using(bucket_id='school-documents' and public.is_active_staff());create policy "Active staff can upload documents" on storage.objects for insert to authenticated with check(bucket_id='school-documents' and public.is_active_staff());create policy "Active staff can update documents" on storage.objects for update to authenticated using(bucket_id='school-documents' and public.is_active_staff()) with check(bucket_id='school-documents' and public.is_active_staff());
